# Generated by Django 4.0.4 on 2022-05-10 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('rfid', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField(null=True)),
                ('purchase_type', models.CharField(choices=[('None', 'None'), ('Owned', 'Owned'), ('Subscription', 'Subscription')], default='None', max_length=30)),
                ('description', models.TextField(null=True)),
                ('serial_no', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(default='index.jpg', upload_to='AssetImages/')),
                ('state', models.CharField(choices=[('Repair', 'Repair'), ('In Use', 'In Use'), ('Defective', 'Defective'), ('Functional', 'Functional')], default='Functional', max_length=30)),
                ('level', models.CharField(choices=[('Level I', '1'), ('Level II', '2'), ('Level III', '3')], default='Level I', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='Apollo', max_length=50, verbose_name='Hospital')),
                ('state', models.CharField(default='Maharashtra', max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('zipcode', models.CharField(default='440013', max_length=6)),
                ('contact_no', models.CharField(default='2222244441', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'location',
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_id', models.CharField(max_length=10, unique=True)),
                ('maintenance_date', models.DateField()),
                ('maintenance_description', models.TextField()),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performed_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'verbose_name_plural': 'Asset Maintenance',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.category'),
        ),
    ]
