# Generated by Django 4.0.1 on 2022-01-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_rfid_alter_asset_serial_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetmaintenance',
            options={'verbose_name_plural': 'Asset Maintenance'},
        ),
    ]
