# Generated by Django 4.0.1 on 2022-01-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_description_asset_purchase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Nagpur', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_no',
            field=models.CharField(default='2222244441', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(default='440013', max_length=6),
        ),
    ]
