# Generated by Django 4.0.2 on 2022-02-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_location_city_location_contact_no_location_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='acquisition_date',
            new_name='purchase_date',
        ),
    ]
